[package]
name = "be_eloistree_wowinteger"
version = "2024.12.5"
edition = "2021"
authors =["Eloi Stree"]
description="Learn to play with code."
license="Beerware"

[dependencies]
rand = "0.8.4"

[profile.dev]
opt-level=0

[profile.release]
opt-level=3